# Generated by Django 5.0.1 on 2024-01-26 15:34

import author.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pengguna', models.CharField(max_length=11)),
                ('nama_pengguna', models.CharField(max_length=50)),
                ('email_pengguna', models.CharField(max_length=50)),
                ('username_pengguna', models.CharField(max_length=50)),
                ('password_pengguna', models.CharField(max_length=255)),
                ('level_pengguna', models.CharField(choices=[('admin', 'Admin'), ('penulis', 'Penulis')], default='penulis', max_length=10)),
                ('status_pengguna', models.CharField(max_length=11)),
                ('foto_pengguna', models.ImageField(upload_to=author.models.user_photo)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
