# Generated by Django 5.0.1 on 2024-01-27 03:43

import author.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_pengguna',
            field=models.ImageField(blank=True, null=True, upload_to=author.models.user_photo),
        ),
    ]
