# Generated by Django 3.1.8 on 2024-01-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_berita', models.DateTimeField(auto_now_add=True)),
                ('judul_berita', models.CharField(max_length=255)),
                ('konten_berita', models.TextField()),
                ('sampul_berita', models.CharField(max_length=255)),
                ('author_berita', models.IntegerField()),
                ('status_berita', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
