# Generated by Django 3.1.8 on 2024-01-22 11:53

import berita.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='sampul_berita',
            field=models.ImageField(blank=True, null=True, upload_to=berita.models.file_image, verbose_name='Sampul Berita'),
        ),
    ]
