# Generated by Django 3.1.8 on 2024-01-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Konsultasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_konsultasi', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=255)),
                ('wa_konsultasi', models.CharField(max_length=15)),
                ('isi_konsultasi', models.TextField()),
                ('tgl_konsultasi', models.DateTimeField(auto_now_add=True)),
                ('tgl_jawab_konsultasi', models.DateField()),
                ('jawab_konsultasi', models.TextField()),
                ('berkas_jawab_konsultasi', models.CharField(max_length=255)),
                ('berkas_konsultasi', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_konsultasi', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
