# Generated by Django 4.2.6 on 2024-01-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("konsultasi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="konsultasi",
            name="berkas_jawab_konsultasi",
            field=models.ImageField(
                blank=True, null=True, upload_to="image/konsultasi-jawab/"
            ),
        ),
        migrations.AlterField(
            model_name="konsultasi",
            name="berkas_konsultasi",
            field=models.ImageField(
                blank=True, null=True, upload_to="image/konsultasi/"
            ),
        ),
    ]
