# Generated by Django 5.0.1 on 2024-01-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pengguna', models.CharField(max_length=11)),
                ('nama_pengguna', models.CharField(max_length=50)),
                ('email_pengguna', models.CharField(max_length=50)),
                ('username_pengguna', models.CharField(max_length=50)),
                ('password_pengguna', models.CharField(max_length=255)),
                ('status_pengguna', models.CharField(max_length=11)),
            ],
        ),
    ]
