# Generated by Django 5.0.1 on 2024-01-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='User',
        ),
    ]
