# Generated by Django 4.2.6 on 2024-01-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Sejarah", "0002_remove_sejarah_id_sejarah"),
    ]

    operations = [
        migrations.AddField(
            model_name="sejarah",
            name="judul_sejarah",
            field=models.TextField(default="Judul"),
        ),
    ]
